# Generated by Django 4.1.5 on 2023-04-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myshopauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
