# Generated by Django 4.1.5 on 2023-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myshopapp', '0004_variation'),
        ('Carts', '0002_rename_quanity_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='Myshopapp.variation'),
        ),
    ]
