# Generated by Django 4.1.5 on 2023-02-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myshopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='slag',
        ),
    ]
