# Generated by Django 4.1.5 on 2023-02-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myshopapp', '0002_rename_slug_product_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slag',
            new_name='slug',
        ),
    ]
