# Generated by Django 4.1.5 on 2023-04-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myshopapp', '0002_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
