# Generated by Django 4.1.5 on 2023-04-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myshopapp', '0003_reviewrating_updated_at_alter_reviewrating_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(max_length=255, upload_to='photos/product')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Myshopapp.product')),
            ],
        ),
    ]
