# Generated by Django 4.1.5 on 2023-03-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_rename_variation_orderproduct_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variations',
            new_name='variation',
        ),
    ]
