# Generated by Django 4.1.5 on 2023-03-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myshopapp', '0001_initial'),
        ('Orders', '0003_rename_variations_orderproduct_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='variation',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='Myshopapp.variation'),
        ),
    ]
