# Generated by Django 4.1.5 on 2023-04-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='province',
        ),
    ]
