# Generated by Django 4.1.5 on 2023-04-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_rename_state_order_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
